CREATE TABLE `Queue` (
	`id` BIGINT(19) NOT NULL AUTO_INCREMENT,
	`type` VARCHAR(50) NOT NULL DEFAULT '0' COLLATE 'utf8mb4_0900_ai_ci',
	`text` LONGTEXT NOT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`author_telegram_id` BIGINT(19) NOT NULL DEFAULT '0',
	`status` VARCHAR(50) NOT NULL DEFAULT 'FALSE' COMMENT 'FALSE, Processing, DONE' COLLATE 'utf8mb4_0900_ai_ci',
	`createdAt` DATETIME NOT NULL DEFAULT 'CURRENT_TIMESTAMP',
	PRIMARY KEY (`id`) USING BTREE
)
COMMENT='Очередь генерации ответа от AI'
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
AUTO_INCREMENT=2
;
